const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Behaviors.bound,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Behaviors.TileMovement,
		C3.Behaviors.scrollto,
		C3.Behaviors.shadowcaster,
		C3.Behaviors.wrap,
		C3.Behaviors.jumpthru,
		C3.Behaviors.MoveTo,
		C3.Plugins.filechooser,
		C3.Plugins.SVGPicture,
		C3.Plugins.Button,
		C3.Plugins.Mouse,
		C3.Plugins.video,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.PlatformInfo,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.TileMovement.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.TileMovement.Cnds.IsMovingDirection,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.TileMovement.Acts.SimulateControl,
		C3.Plugins.System.Cnds.CompareTime,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.System.Cnds.Else
	];
};
self.C3_JsPropNameTable = [
	{Fixar: 0},
	{RestritoAoLayout: 0},
	{Sprite2: 0},
	{tilesheet_complete_2X: 0},
	{Sample: 0},
	{Preview: 0},
	{Sample1: 0},
	{Sample2: 0},
	{Sprite: 0},
	{Sprite3: 0},
	{Sólido: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Teclado: 0},
	{Sprite14: 0},
	{MovimentoEmGrid: 0},
	{CentrarEm: 0},
	{Sprite15: 0},
	{ProjetorDeSombra: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{DarAVolta: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{PularAtravés: 0},
	{Sprite27: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{MoverPara: 0},
	{Sprite30: 0},
	{Sprite31: 0},
	{Sprite32: 0},
	{Sprite33: 0},
	{SelecionadorDeArquivo: 0},
	{ImagemSVG: 0},
	{Sprite36: 0},
	{Sprite35: 0},
	{Sprite37: 0},
	{Sprite38: 0},
	{Sprite39: 0},
	{Sprite41: 0},
	{Sprite42: 0},
	{Sprite43: 0},
	{Sprite44: 0},
	{Sprite45: 0},
	{Sprite46: 0},
	{Sprite47: 0},
	{Sprite48: 0},
	{Sprite49: 0},
	{Sprite50: 0},
	{Sprite40: 0},
	{Sprite51: 0},
	{Botão: 0},
	{Sprite52: 0},
	{Mouse: 0},
	{Sprite53: 0},
	{Vídeo2: 0},
	{Navegador: 0},
	{Sprite54: 0},
	{Sprite55: 0},
	{Sprite56: 0},
	{Sprite57: 0},
	{Sprite58: 0},
	{Sprite59: 0},
	{Sprite60: 0},
	{Sprite61: 0},
	{Toque: 0},
	{Áudio: 0},
	{InformaçãoDaPlataforma: 0},
	{memoriasColetadas: 0}
];

self.InstanceType = {
	Sprite2: class extends self.ISpriteInstance {},
	tilesheet_complete_2X: class extends self.ISpriteInstance {},
	Sample: class extends self.ISpriteInstance {},
	Preview: class extends self.ISpriteInstance {},
	Sample1: class extends self.ISpriteInstance {},
	Sample2: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	SelecionadorDeArquivo: class extends self.IFileChooserInstance {},
	ImagemSVG: class extends self.ISVGPictureInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	Sprite39: class extends self.ISpriteInstance {},
	Sprite41: class extends self.ISpriteInstance {},
	Sprite42: class extends self.ISpriteInstance {},
	Sprite43: class extends self.ISpriteInstance {},
	Sprite44: class extends self.ISpriteInstance {},
	Sprite45: class extends self.ISpriteInstance {},
	Sprite46: class extends self.ISpriteInstance {},
	Sprite47: class extends self.ISpriteInstance {},
	Sprite48: class extends self.ISpriteInstance {},
	Sprite49: class extends self.ISpriteInstance {},
	Sprite50: class extends self.ISpriteInstance {},
	Sprite40: class extends self.ISpriteInstance {},
	Sprite51: class extends self.ISpriteInstance {},
	Botão: class extends self.IButtonInstance {},
	Sprite52: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Sprite53: class extends self.ISpriteInstance {},
	Vídeo2: class extends self.IWorldInstance {},
	Navegador: class extends self.IInstance {},
	Sprite54: class extends self.ISpriteInstance {},
	Sprite55: class extends self.ISpriteInstance {},
	Sprite56: class extends self.ISpriteInstance {},
	Sprite57: class extends self.ISpriteInstance {},
	Sprite58: class extends self.ISpriteInstance {},
	Sprite59: class extends self.ISpriteInstance {},
	Sprite60: class extends self.ISpriteInstance {},
	Sprite61: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {},
	Áudio: class extends self.IInstance {},
	InformaçãoDaPlataforma: class extends self.IInstance {}
}